{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      volumes:
        - name: dsl
          emptyDir: {}
      initContainers:
        - name: git-clone-dsl
          image: alpine/git:latest
          volumeMounts:
          - name: dsl
            mountPath: /DSL
          command:
            - sh
            - -c
            - |
                git clone --single-branch --depth 1 --branch wip \
                  https://github.com/rootcodelabs/LLM-Module /tmp/rag &&

                cp -r /tmp/rag/DSL/Resql/* /DSL/

                
                
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.resql.registry }}/{{ .Values.images.resql.repository }}:{{ .Values.images.resql.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: logging.level.root
              value: "{{ .Values.env.LOGGING_LEVEL_ROOT }}"
            - name: SQLMS_DATASOURCES_0_NAME
              value: "{{ .Values.env.SQLMS_DATASOURCES_0_NAME }}"
            - name: SQLMS_DATASOURCES_0_JDBCURL
              value: "{{ .Values.env.SQLMS_DATASOURCES_0_JDBCURL }}"
            - name: SQLMS_DATASOURCES_0_USERNAME
              value: "{{ .Values.env.SQLMS_DATASOURCES_0_USERNAME }}"
            # Sensitive env from Kubernetes Secret
            - name: SQLMS_DATASOURCES_0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resql-secrets
                  key: SQLMS_DATASOURCES_0_PASSWORD
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT
              value: "{{ .Values.env.LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT }}"
            - name: SQLMS_SAVED_QUERIES_DIR
              value: "/DSL"
          volumeMounts:
            - name: dsl
              mountPath: /DSL
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
      
{{- end }}
