apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.release_name }}-config
  labels:
    app: {{ .Values.release_name }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}