apiVersion: v1
kind: Secret
metadata:
  name: s3-ferry-secrets
  labels:
    app: "{{ .Values.release_name }}"
type: Opaque
stringData:
  S3_SECRET_ACCESS_KEY: "<SET_ME>"
  S3_ACCESS_KEY_ID: "<SET_ME>"
  GF_SECURITY_ADMIN_USER: "<SET_ME>"
  GF_SECURITY_ADMIN_PASSWORD: "<SET_ME>"
