-- liquibase formatted sql

-- changeset Erangi Ariyasena:rag-script-v5-changeset1
CREATE TABLE public.prompt_configuration (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    prompt TEXT
);

