apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release_name }}
  labels:
    app: {{ .Values.release_name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.release_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.release_name }}
    spec:
      containers:
        - name: {{ .Values.release_name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki/local-config.yaml
            {{- if .Values.persistence.enabled }}
            - name: storage
              mountPath: /loki
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: loki-config
        {{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: loki-storage
        {{- end }}
      