FROM node:22.0.0-alpine AS image
WORKDIR /app
COPY ./package.json ./package-lock.json ./

FROM image AS build
RUN npm ci --legacy-peer-deps
COPY . .
RUN ./node_modules/.bin/vite build --mode=development

EXPOSE 3001

ENV REACT_APP_ENABLE_HIDDEN_FEATURES TRUE

CMD ["npm", "run", "dev"]
