{{- if .Values.notifications.opensearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: notifications-env-secret
  labels:
    app: {{ .Values.release_name }}
   
type: Opaque
data:
  OPENSEARCH_USERNAME: {{ .Values.notifications.opensearch.username | b64enc }}
  OPENSEARCH_PASSWORD: {{ .Values.notifications.opensearch.password | b64enc }}
{{- end }}