apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release_name }}
  labels:
    app: {{ .Values.release_name }}
    component: vault-agent-llm
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.release_name }}
      component: vault-agent-llm
  template:
    metadata:
      labels:
        app: {{ .Values.release_name }}
        component: vault-agent-llm
    spec:
      {{- if .Values.affinity.enabled }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.vault.serviceName }}
            topologyKey: kubernetes.io/hostname
      {{- end }}
      volumes:
        {{- if .Values.volumes.agentCredentials.enabled }}
        - name: vault-agent-creds
          persistentVolumeClaim:
            claimName: vault-agent-creds
        {{- end }}
        {{- if .Values.volumes.agentToken.enabled }}
        - name: vault-agent-token
          persistentVolumeClaim:
            claimName: vault-agent-token
        {{- end }}
        {{- if .Values.volumes.agentConfig.enabled }}
        - name: vault-agent-config
          configMap:
            name: {{ .Values.release_name }}-config
            defaultMode: 0644
        {{- end }}
      containers:
      - name: vault-agent
        image: "{{ .Values.images.vault.registry }}/{{ .Values.images.vault.repository }}:{{ .Values.images.vault.tag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: 
          - vault
          - agent
          - -config=/agent/config/agent.hcl
          - -log-level=info
        env:
          - name: VAULT_ADDR
            value: {{ .Values.vault.addr | quote }}
          - name: VAULT_SKIP_VERIFY
            value: "true"
        volumeMounts:
          {{- if .Values.volumes.agentCredentials.enabled }}
          - name: vault-agent-creds
            mountPath: {{ .Values.volumes.agentCredentials.mountPath }}
            readOnly: true
          {{- end }}
          {{- if .Values.volumes.agentToken.enabled }}
          - name: vault-agent-token
            mountPath: {{ .Values.volumes.agentToken.mountPath }}
          {{- end }}
          {{- if .Values.volumes.agentConfig.enabled }}
          - name: vault-agent-config
            mountPath: {{ .Values.volumes.agentConfig.mountPath }}
            readOnly: true
          {{- end }}
        {{- if .Values.probes.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.livenessProbe.httpGet.path }}
            port: {{ .Values.probes.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
        {{- end }}
        {{- if .Values.probes.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readinessProbe.httpGet.path }}
            port: {{ .Values.probes.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        securityContext:
          capabilities:
            add:
              - IPC_LOCK