enabled: true
release_name: "component-byk-liquibase"
backoffLimit: 3

images:
  scope:
    repository: "liquibase/liquibase"
    tag: "4.33.0"

env:
  - name: LIQUIBASE_URL
    value: "jdbc:postgresql://rag-search-db:5432/llm_production"
  - name: LIQUIBASE_CHANGELOG_FILE
    value: changelog.yaml



pullPolicy: IfNotPresent

podAnnotations: 
  dsl-checksum: "211bdc77c12b"