apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  labels:
    app: "{{ .Values.release_name }}"
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "<SET_ME>"
  GF_SECURITY_ADMIN_PASSWORD: "<SET_ME>"
