{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-web-secrets
  labels:
    app: "{{ .Values.release_name }}"
    component: langfuse-web
type: Opaque
stringData:
  DATABASE_URL: "<SET_ME>"
  NEXTAUTH_SECRET: "<SET_ME>"
  ENCRYPTION_KEY: "<SET_ME>"
  SALT: "<SET_ME>"
  CLICKHOUSE_MIGRATION_URL: "<SET_ME>"
  CLICKHOUSE_USER: "<SET_ME>"
  CLICKHOUSE_PASSWORD: "<SET_ME>"
  LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: "<SET_ME>"
  LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: "<SET_ME>"
  LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: "<SET_ME>"
  LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: "<SET_ME>"
  LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID: "<SET_ME>"
  LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY: "<SET_ME>"
  REDIS_AUTH: "<SET_ME>"
{{- end }}
