apiVersion: v1
kind: Secret
metadata:
  name: tim-env-secret
type: Opaque
stringData:
  oauth2_client_secret: "<SET_ME>"
  jwt_integration_key_store_password: "<SET_ME>"
  POSTGRES_PASSWORD: "<SET_ME>"

