apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gui-ingress
  namespace: llm-module
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /rag-search
        pathType: Prefix
        backend:
          service:
            name: gui
            port:
              number: 3003
  