{{- range .Values.databases }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  labels:
    app: {{ .name }}
type: Opaque
data:
  password: {{ .password | b64enc | quote }}
---
{{- end }}
