replicas: 1
enabled: true

images:
  redis:
    registry: "docker.io"
    repository: "redis"
    tag: "7"

release_name: "redis"

service:
  type: ClusterIP
  port: 6379

auth:
  enabled: true

# Reference to Kubernetes Secret
envFrom:
  - secretRef:
      name: redis-secrets

# Resource configuration
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "200m"

pullPolicy: IfNotPresent

healthcheck:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1