apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release_name }}
  labels:
    app: {{ .Values.release_name }}
spec:
  type: {{ .Values.opensearch.service.type }}
  ports:
  - port: {{ .Values.opensearch.service.api }}
    targetPort: {{ .Values.opensearch.ports.api }}
    protocol: TCP
    name: api
  - port: {{ .Values.opensearch.service.performance }}
    targetPort: {{ .Values.opensearch.ports.performance }}
    protocol: TCP
    name: performance
  selector:
    app: {{ .Values.release_name }}