INSERT INTO services (
    name,
    description,
    service_id,
    ruuter_type,
    current_state,
    is_common,
    slot,
    entities,
    examples,
    structure,
    endpoints,
    created_at,
    updated_at
) VALUES (
    :name,
    :description,
    :service_id,
    :ruuter_type::ruuter_request_type,
    :current_state::service_state,
    :is_common,
    :slot,
    ARRAY[:entities]::text[],
    ARRAY[:examples]::text[],
    :structure::json,
    :endpoints::json,
    :created_at::timestamp with time zone,
    :updated_at::timestamp with time zone
) RETURNING 
    id,
    name,
    description,
    service_id,
    ruuter_type,
    current_state,
    is_common,
    slot,
    entities,
    examples,
    structure,
    endpoints,
    created_at,
    updated_at;
