INSERT INTO llm_connections (
    llm_platform,
    llm_model,
    embedding_platform,
    embedding_model,
    monthly_budget,
    environment,
    connection_status,
    created_at,
    deployment_name,
    target_uri,
    api_key,
    secret_key,
    access_key,
    embedding_model_api_key
) VALUES (
    :llm_platform,
    :llm_model,
    :embedding_platform,
    :embedding_model,
    :monthly_budget,
    :environment,
    :connection_status,
    :created_at::timestamp with time zone,
    :deployment_name,
    :target_uri,
    :api_key,
    :secret_key,
    :access_key,
    :embedding_model_api_key
) RETURNING 
    id, 
    llm_platform, 
    llm_model, 
    embedding_platform, 
    embedding_model, 
    monthly_budget, 
    environment, 
    connection_status, 
    created_at,
    deployment_name,
    target_uri,
    api_key,
    secret_key,
    access_key,
    embedding_model_api_key;
