{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
  labels:
    app: "{{ .Values.release_name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.authentication.image.repository }}:{{ .Values.authentication.image.tag }}"
          imagePullPolicy: {{ .Values.authentication.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.authentication.environment.serverPort | quote }}
            - name: TIM_SERVICE_URL
              value: {{ .Values.authentication.environment.timServiceUrl | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.authentication.environment.corsOrigins | quote }}
        
{{- end }}